# Generated by Django 6.0 on 2026-03-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0002_student_mentor_id_student_mentor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='bucket',
            field=models.CharField(choices=[('C0', 'C0 BUCKET'), ('C1', 'C1 BUCKET'), ('C2', 'C2 BUCKET'), ('C3', 'C3 BUCKET')], default='C0', max_length=2),
        ),
    ]
