# Generated by Django 6.0 on 2026-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0003_subject_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.CharField(choices=[('Embedded Systems', 'Embedded Systems'), ('VLSI Design', 'VLSI Design'), ('Signal Processing', 'Signal Processing'), ('Communication Systems', 'Communication Systems'), ('IoT', 'IoT'), ('Robotics', 'Robotics')], default='Embedded Systems', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='specialization',
            field=models.CharField(choices=[('Embedded Systems', 'Embedded Systems'), ('VLSI Design', 'VLSI Design'), ('Signal Processing', 'Signal Processing'), ('Communication Systems', 'Communication Systems'), ('IoT', 'IoT'), ('Robotics', 'Robotics')], default='Embedded Systems', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='bucket',
            field=models.CharField(choices=[('C0', 'C0 BUCKET'), ('C1', 'C1 BUCKET'), ('C2', 'C2 BUCKET'), ('C3', 'C3 BUCKET'), ('C4', 'C4 BUCKET'), ('C5', 'C5 BUCKET'), ('C6', 'C6 BUCKET'), ('C7', 'C7 BUCKET'), ('C8', 'C8 BUCKET'), ('C9', 'C9 BUCKET')], default='C0', max_length=2),
        ),
    ]
