# Generated by Django 6.0 on 2026-03-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0004_student_specialization_subject_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(choices=[('Internet of Things (IOT)', 'Internet of Things (IOT)'), ('Renewable Energy & Smart Cities', 'Renewable Energy & Smart Cities'), ('VLSI', 'VLSI'), ('Robotics & Automation', 'Robotics & Automation'), ('Signal Processing', 'Signal Processing'), ('RF & Microwave', 'RF & Microwave'), ('Data Communications', 'Data Communications'), ('Computer communications & 5G Technologies', 'Computer communications & 5G Technologies'), ('Bio-Medical Instrumentation', 'Bio-Medical Instrumentation'), ('Artificial Intelligence & Intelligent Process Automation', 'Artificial Intelligence & Intelligent Process Automation'), ('Cyber Security & Block Chain Technology', 'Cyber Security & Block Chain Technology'), ('Data Science & Big Data Analytics', 'Data Science & Big Data Analytics'), ('Graphics, Gaming & UX Design', 'Graphics, Gaming & UX Design')], default='Embedded Systems', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='specialization',
            field=models.CharField(choices=[('Internet of Things (IOT)', 'Internet of Things (IOT)'), ('Renewable Energy & Smart Cities', 'Renewable Energy & Smart Cities'), ('VLSI', 'VLSI'), ('Robotics & Automation', 'Robotics & Automation'), ('Signal Processing', 'Signal Processing'), ('RF & Microwave', 'RF & Microwave'), ('Data Communications', 'Data Communications'), ('Computer communications & 5G Technologies', 'Computer communications & 5G Technologies'), ('Bio-Medical Instrumentation', 'Bio-Medical Instrumentation'), ('Artificial Intelligence & Intelligent Process Automation', 'Artificial Intelligence & Intelligent Process Automation'), ('Cyber Security & Block Chain Technology', 'Cyber Security & Block Chain Technology'), ('Data Science & Big Data Analytics', 'Data Science & Big Data Analytics'), ('Graphics, Gaming & UX Design', 'Graphics, Gaming & UX Design')], default='Embedded Systems', max_length=100),
        ),
    ]
