# Generated by Django 6.0 on 2026-03-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0006_alter_student_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(choices=[('IOT', 'Internet of Things (IoT)'), ('RESC', 'Renewable Energy & Smart Cities'), ('VLSI', 'VLSI'), ('RA', 'Robotics & Automation'), ('SP', 'Signal Processing'), ('RF', 'RF & Microwave'), ('DC', 'Data Communications'), ('CC5G', 'Computer Communications & 5G Technologies'), ('BMI', 'Bio-Medical Instrumentation'), ('AIIPA', 'Artificial Intelligence & Intelligent Process Automation'), ('CSBC', 'Cyber Security & Block Chain Technology'), ('DSBDA', 'Data Science & Big Data Analytics'), ('GGUX', 'Graphics, Gaming & UX Design')], max_length=100),
        ),
    ]
