# Generated by Django 6.0 on 2026-03-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0007_remove_subject_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='counselor_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='counselor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
