# Generated by Django 6.0 on 2026-03-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0008_student_counselor_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='counselor_contact_number',
            new_name='counsellor_contact_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='counselor_email',
            new_name='counsellor_email',
        ),
    ]
