# Generated by Django 6.0 on 2026-03-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0009_rename_counselor_contact_number_student_counsellor_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='counsellor_contact_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='counsellor_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='bucket',
        ),
    ]
