# Generated by Django 6.0 on 2026-03-14 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('counsellor_app', '0001_initial'),  # Removed dependency on deleted app
        ('portal_app', '0010_remove_student_counsellor_contact_number_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='student',
        #     name='counsellor',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='counsellor_app.counsellor'),
        # ),  # Legacy field neutralized
    ]
