# Generated by Django 6.0 on 2026-03-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0011_student_counsellor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mentor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
