# Generated by Django 6.0 on 2026-03-14 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0012_student_mentor_email_alter_student_mentor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_id', models.CharField(max_length=100, unique=True)),
                ('mentor_name', models.CharField(max_length=200)),
                ('mentor_email', models.EmailField(max_length=254)),
                ('mentor_phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='student',
        #     name='counsellor',
        # ),
        migrations.RemoveField(
            model_name='student',
            name='mentor_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mentor_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mentor_name',
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='portal_app.mentor'),
        ),
    ]
