# Generated by Django 6.0.3 on 2026-03-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0014_remove_student_mentor_student_mentor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='bucket',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
