# Generated by Django 6.0.3 on 2026-03-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0015_subject_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mentor_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
