# Generated by Django 6.0.3 on 2026-03-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0016_student_mentor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=200)),
            ],
        ),
    ]
