# Generated by Django 6.0.3 on 2026-03-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0017_subjectmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
