# Generated by Django 6.0.3 on 2026-03-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0018_student_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cluster1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='cluster2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='cluster1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='cluster2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
