# Generated by Django 6.0.3 on 2026-03-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0019_subject_cluster1_subject_cluster2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmaster',
            name='cluster1',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='cluster2',
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='cluster_end',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='cluster_start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='department',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
