# Generated by Django 6.0.3 on 2026-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0020_remove_subjectmaster_cluster1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmaster',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectmaster',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectmaster',
            name='subject_id',
            field=models.CharField(max_length=50),
        ),
    ]
