# Generated by Django 6.0.3 on 2026-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0021_subjectmaster_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('bucket', models.CharField(max_length=20)),
                ('subject_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='bucket',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='cluster1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='cluster2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subjectmaster',
            name='specialization',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
