# Generated by Django 6.0.3 on 2026-03-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0022_specializationmapping_alter_subject_bucket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmaster',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectmaster',
            name='specialization',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectmaster',
            name='subject_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectmaster',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='subjectmaster',
            unique_together={('subject_id', 'department', 'specialization')},
        ),
    ]
