# Generated by Django 6.0.3 on 2026-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0024_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='cluster1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='cluster2',
        ),
        migrations.AddField(
            model_name='subject',
            name='cluster1_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='cluster1_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='cluster2_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='cluster2_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
