# Generated by Django 6.0.3 on 2026-03-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0025_remove_subject_cluster1_remove_subject_cluster2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmaster',
            name='cluster_end',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='cluster_start',
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='cluster1_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='cluster1_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='cluster2_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='cluster2_start',
            field=models.IntegerField(default=0),
        ),
    ]
